### ISSUE TITLE
[Lua - LevelLoader - Crash] Http savefile download - Lack of failsafe can lead to crashes   

### ISSUE THREAD

**Issue by 3ti65** [BF3RM/CustomLevelLoader#16]
"Http request failed with error 'timeout'"

If the mirror with the savefiles is not up or the http request fails on either server or client, the http will timeout and people will be kicked from the server because of the desync of level data.

**Comment by FlashHit** [comment]
We need alternative mirrors then.

**Comment by 3ti65** [comment]
I can get an alternative mirror done. I think we should kick people deliberately from the server if the DL fails, with a clear message. So it doesn't just crash.

**Comment by FlashHit** [comment]
> I think we should kick people deliberately from the server if the DL fails, with a clear message.

Then we need a preset (can be empty) for XP4_Parl, cuz otherwise it would kick all players on that map

**Comment by 3ti65** [comment]
you're correct. not sure how to solve this atm. will have to happen after playtest
